/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CartIndexRouteImport } from './routes/cart/index'
import { Route as ShopShoseRouteImport } from './routes/shop/shose'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as AccountRegisterRouteImport } from './routes/account/register'
import { Route as AccountLoginRouteImport } from './routes/account/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartIndexRoute = CartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopShoseRoute = ShopShoseRouteImport.update({
  id: '/shop/shose',
  path: '/shop/shose',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRegisterRoute = AccountRegisterRouteImport.update({
  id: '/account/register',
  path: '/account/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/account/login',
  path: '/account/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/shose': typeof ShopShoseRoute
  '/cart': typeof CartIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/shose': typeof ShopShoseRoute
  '/cart': typeof CartIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account/login': typeof AccountLoginRoute
  '/account/register': typeof AccountRegisterRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/shose': typeof ShopShoseRoute
  '/cart/': typeof CartIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account/login'
    | '/account/register'
    | '/collections/$slug'
    | '/shop/shose'
    | '/cart'
    | '/collections'
    | '/shop'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account/login'
    | '/account/register'
    | '/collections/$slug'
    | '/shop/shose'
    | '/cart'
    | '/collections'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/account/login'
    | '/account/register'
    | '/collections/$slug'
    | '/shop/shose'
    | '/cart/'
    | '/collections/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountRegisterRoute: typeof AccountRegisterRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ShopShoseRoute: typeof ShopShoseRoute
  CartIndexRoute: typeof CartIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/shose': {
      id: '/shop/shose'
      path: '/shop/shose'
      fullPath: '/shop/shose'
      preLoaderRoute: typeof ShopShoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/register': {
      id: '/account/register'
      path: '/account/register'
      fullPath: '/account/register'
      preLoaderRoute: typeof AccountRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/login': {
      id: '/account/login'
      path: '/account/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountRegisterRoute: AccountRegisterRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ShopShoseRoute: ShopShoseRoute,
  CartIndexRoute: CartIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
